part of 'app_pages.dart';

abstract class Routes {
  Routes._();
  static const SPLASH = _Paths.SPLASH;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const HOME = _Paths.HOME;
  static const FAVORITE = _Paths.FAVORITE;
  static const WALLET = _Paths.WALLET;
  static const PROFILE = _Paths.PROFILE;
  static const FAVOURITE = _Paths.FAVOURITE;
  static const TRAINER_DETAILS = _Paths.TRAINER_DETAILS;
  static const MESSAGE_SCREEN = _Paths.MESSAGE_SCREEN;
  static const LOGIN = _Paths.LOGIN;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const SIGN_UP = _Paths.SIGN_UP;
  static const WELCOME = _Paths.WELCOME;
  static const GET_STARTED = _Paths.GET_STARTED;
  static const GENDER_SELECTION = _Paths.GENDER_SELECTION;
  static const AGE_INPUT = _Paths.AGE_INPUT;
  static const WEIGHT_INPUT = _Paths.WEIGHT_INPUT;
  static const HEIGHT_INPUT = _Paths.HEIGHT_INPUT;
  static const FITNESS_GOAL = _Paths.FITNESS_GOAL;
  static const ACTIVITY_LEVEL = _Paths.ACTIVITY_LEVEL;
  static const FITNESS_LEVEL = _Paths.FITNESS_LEVEL;
  static const NOTIFICATION_PERMISSION = _Paths.NOTIFICATION_PERMISSION;
  static const PROFILE_SUMMARY = _Paths.PROFILE_SUMMARY;
  static const BOOK_SESSION = _Paths.BOOK_SESSION;
  static const MY_BOOKINGS = _Paths.MY_BOOKINGS;
  static const SEARCH = _Paths.SEARCH;
  static const SETTINGS = _Paths.SETTINGS;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const TX_HISTORY = _Paths.TX_HISTORY;
  static const ALL_SESSIONS = _Paths.ALL_SESSIONS;
  static const TRAINER_DASHBOARD = _Paths.TRAINER_DASHBOARD;
  static const TRAINER_AVAILABILITY = _Paths.TRAINER_AVAILABILITY;
  static const ADMIN_DASHBOARD = _Paths.ADMIN_DASHBOARD;
  static const STREAK_DETAILS = _Paths.STREAK_DETAILS;
  static const GOALS_DETAILS = _Paths.GOALS_DETAILS;
}

abstract class _Paths {
  _Paths._();
  static const SPLASH = '/splash';
  static const ONBOARDING = '/onboarding';
  static const HOME = '/home';
  static const FAVORITE = '/favorite';
  static const WALLET = '/wallet';
  static const PROFILE = '/profile';
  static const FAVOURITE = '/favourite';
  static const TRAINER_DETAILS = '/trainer-details';
  static const MESSAGE_SCREEN = '/message-screen';
  static const LOGIN = '/login';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const SIGN_UP = '/sign-up';
  static const WELCOME = '/welcome';
  static const GET_STARTED = '/get-started';
  static const GENDER_SELECTION = '/gender-selection';
  static const AGE_INPUT = '/age-input';
  static const WEIGHT_INPUT = '/weight-input';
  static const HEIGHT_INPUT = '/height-input';
  static const FITNESS_GOAL = '/fitness-goal';
  static const ACTIVITY_LEVEL = '/activity-level';
  static const FITNESS_LEVEL = '/fitness-level';
  static const NOTIFICATION_PERMISSION = '/notification-permission';
  static const PROFILE_SUMMARY = '/profile-summary';
  static const BOOK_SESSION = '/book-session';
  static const MY_BOOKINGS = '/my-bookings';
  static const ALL_SESSIONS = '/all-sessions';
  static const SEARCH = '/search';
  static const SETTINGS = '/settings';
  static const NOTIFICATIONS = '/notifications';
  static const TX_HISTORY = '/tx-history';
  static const TRAINER_DASHBOARD = '/trainer-dashboard';
  static const TRAINER_AVAILABILITY = '/trainer-availability';
  static const ADMIN_DASHBOARD = '/admin-dashboard';
  static const STREAK_DETAILS = '/streak-details';
  static const GOALS_DETAILS = '/goals-details';
}
